server:
  servlet:
    encoding:
      charset: utf-8
      force: true
    # url rewrite 문제 해결
    session:
      tracking-modes: cookie
  port: 5000 # 배포하면 방화벽오픈돼있는 포트가 기본 5000이다.

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_HOST}:3306/blogdb
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 10
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: INFO # ?에 들어가는 것을 보여줌
    shop.mtcoding.blog: INFO